-------------------------------------------------------------------------------
-- userconfig.lua, master copy
-- If you want to change your settings, do not look here.
-- what you want is the user-generated config, which you can find at
-- love.filesystem.getSaveDirectory() .. "/userconfig.lua"
-- to reset your config just delete that file
-------------------------------------------------------------------------------
return {
	phoneHome      = false,
	bloom          = true,
	defaultleft    = 'mouse',
	defaultright   = 'ai',
	fullscreen     = false,
	windowedMode   = {1280*.66, 720*.66},
	fullscreenMode = nil, -- autogenerated, then saved
	fsaa           = 2
}
